### ISSUE TITLE
License to use?

### ISSUE THREAD

**Issue by KeyboardDanni** [tiby312/dinotree_alg#74]
Hi,

I'm looking for a good collision (not physics!) system for my game engine. I took a look at dinotree and it looks like it fits my needs performance-wise. The big question that remains for me is licensing. The crate metadata says MIT/Apache-2.0, but there are no license files or license headers in the source code itself. Combine this with the impressive algorithm write-up, and I'm wondering if this library is intended for something other than general consumption.

Is it okay to use this library in my own projects?

**Comment by tiby312** [comment]
Absolutely free to use. I haven't gotten around to adding the MIT license headers.

**Comment by KeyboardDanni** [comment]
Why not just provide a LICENSE file at the repository root? Would be easier, and having the license text somewhere would be better than none.

**Comment by tiby312** [comment]
you're right that's way easier i'll do that thanks

**Comment by tiby312** [comment]
put mit license in source
